package mywebservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HellowServiceService", targetNamespace = "http://MyWebService/", wsdlLocation = "http://localhost:9527/Saber?wsdl")
public class HellowServiceService
    extends Service
{

    private final static URL HELLOWSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWSERVICESERVICE_EXCEPTION;
    private final static QName HELLOWSERVICESERVICE_QNAME = new QName("http://MyWebService/", "HellowServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9527/Saber?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWSERVICESERVICE_WSDL_LOCATION = url;
        HELLOWSERVICESERVICE_EXCEPTION = e;
    }

    public HellowServiceService() {
        super(__getWsdlLocation(), HELLOWSERVICESERVICE_QNAME);
    }

    public HellowServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWSERVICESERVICE_QNAME, features);
    }

    public HellowServiceService(URL wsdlLocation) {
        super(wsdlLocation, HELLOWSERVICESERVICE_QNAME);
    }

    public HellowServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWSERVICESERVICE_QNAME, features);
    }

    public HellowServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HellowServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HellowService
     */
    @WebEndpoint(name = "HellowServicePort")
    public HellowService getHellowServicePort() {
        return super.getPort(new QName("http://MyWebService/", "HellowServicePort"), HellowService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HellowService
     */
    @WebEndpoint(name = "HellowServicePort")
    public HellowService getHellowServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://MyWebService/", "HellowServicePort"), HellowService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWSERVICESERVICE_EXCEPTION!= null) {
            throw HELLOWSERVICESERVICE_EXCEPTION;
        }
        return HELLOWSERVICESERVICE_WSDL_LOCATION;
    }

}
