
package MyWebService.make;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HellowService", targetNamespace = "http://MyWebService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HellowService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHellow", targetNamespace = "http://MyWebService/", className = "mywebservice.SayHellow")
    @ResponseWrapper(localName = "sayHellowResponse", targetNamespace = "http://MyWebService/", className = "mywebservice.SayHellowResponse")
    @Action(input = "http://MyWebService/HellowService/sayHellowRequest", output = "http://MyWebService/HellowService/sayHellowResponse")
    public String sayHellow(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
