package com.saber.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * 只需要生成接口文件
 *  文件原来的路径   H:\apache-cxf-2.4.2\bin
 */

/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-10-12T16:50:04.916+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://service.saber.com/", name = "HellowService")
@XmlSeeAlso({})
public interface HellowService {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.saber.com/", className = "com.saber.service.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.saber.com/", className = "com.saber.service.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String sayHello(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
